#!/bin/bash
USER=$1
COMMAND=("${@:2}")
if [ -z "$USER" ] || [ -z "$COMMAND" ]
then
        echo 'Not enough parameters:'
        echo 'sudo-x user command [command parameters]'
        exit 1
fi

function exitWithErrorMessage
{
	echo $1
	exit 1
}

TMP_FOLDER=/dev/shm

LOCK_FOLDER=$TMP_FOLDER/xhost-locks.$(whoami).$USER/
if [ ! -d "$LOCK_FOLDER" ]
then
	mkdir "$LOCK_FOLDER" || exitWithErrorMessage "Error: Could not create lock folder"
fi

INSTANCE_LOCK_FILE="$LOCK_FOLDER/$$"

function isLockFolderEmpty
{
	DIR_LISTING=$(ls "$LOCK_FOLDER")
	if [ -z "$DIR_LISTING" ]
	then
		return 0
	else
		return 1
	fi
}

if isLockFolderEmpty
then
	echo "Giving $USER xauth key"
	XAUTH_KEY=$(xauth list | grep $(uname -n) | sed -n '1,1p' | cut -d ' ' -f 5)
	sudo -u "$USER" xauth add $DISPLAY . $XAUTH_KEY
fi
touch "$INSTANCE_LOCK_FILE" || exitWithErrorMessage "Error: Could not create lock file"

sudo -H -u "$USER" "${COMMAND[@]}"

rm "$INSTANCE_LOCK_FILE"
if isLockFolderEmpty
then
	echo "Taking $USER xauth key"
	sudo -u "$USER" xauth remove $DISPLAY
	rmdir $LOCK_FOLDER
fi
